version: '2'
services:
  php:
    build:
      context: .
      args:
        - UID
    volumes:
      - .:/var/www
    ports:
      - 8080:80
    networks:
      - base
  postgres:
    image: postgres:9.5
    environment:
      - POSTGRES_USER=mvlabs
      - POSTGRES_PASSWORD=mvlabs
      - POSTGRES_DB=mvlabs
    networks:
      - base
    ports:
      - 5432:5432
  pgadmin:
    image: fenglc/pgadmin4
    networks:
      - base
    depends_on:
      - postgres
    ports:
      - 8081:5050
networks:
  base: